### ISSUE TITLE
Composer failed to resolve npm-asset/jsoneditor

### ISSUE THREAD

**Issue by safdar-tp** [dmitry-kulikov/yii2-json-editor#1]
### What steps will reproduce the problem?
composer install
### What is the expected result?
should install dependencies
### What do you get instead?
`Your requirements could not be resolved to an installable set of packages.`

  Problem 1
    - Installation request for kdn/yii2-json-editor 1.0.2 -> satisfiable by kdn/yii2-json-editor[1.0.2].
    - kdn/yii2-json-editor 1.0.2 requires npm-asset/jsoneditor 5.* -> no matching package found.

### Additional info

| Q                   | A 
|---------------------|---
| Extension version   |  1.0.2
| Yii version         |  yii2-app-advanced
| JSON editor version | 1.0.2
| PHP version         |  5.6.30
| HHVM version        | 
| Operating system    |  Ubuntu

**Comment by dmitry-kulikov** [comment]
Please make sure you have installed composer asset plugin `fxp/composer-asset-plugin`
```
composer global require "fxp/composer-asset-plugin:^1.2.0"
```
and version is actual, since some old versions have bugs.
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-from-composer
Also you can try to update composer itself
```
composer self-update
```
I just tested installation, works for me.

**Comment by safdar-tp** [comment]
yup It works. I forgot to run  `composer global require "fxp/composer-asset-plugin:^1.2.0"`

Thanks.
